---
- hosts: vm 
  become: true 
  connection: ssh
  tasks:
   - name: git checkout 
     ansible.builtin.git:
      repo: https://github.com/manjarisri/ans.git
      dest: /home/ubuntu/ans
      single_branch: yes
      version: deploy
      
#    - name: Install dep
#      pip:
#         name:
#           - Flask==2.3.2
#           - WTForms==3.0.1
#           - SQLAlchemy==2.0.12
#           - bcrypt==3.2.0
#           - Flask-Bcrypt==1.0.1
#           - Flask-Login==0.6.2
#           - flask_wtf==1.1.1
#           - email-validator==2.0.0.post2
#         state: present
        
   - name: deploy app
     command: python3 /home/ubuntu/ans/todo.py
     
