---
- hosts: vm 
  become: true 
  connection: ssh
#   gather_facts: no
  tasks:
   - name: copy app files
     copy:
      src: ./
      dest: /var/www/myapp

   - name: deploy app
     command: python3 /var/www/myapp/todo.py
