---
- hosts: vm 
  become: true 
  connection: ssh
  tasks:
    - name: git checkout 
      ansible.builtin.git:
        repo: https://github.com/manjarisri/ans.git
        dest: /home/ubuntu/ans
        single_branch: yes
        version: deploy
     
    - name: start docker container
      docker_container:
        name: docker_con 
        exposed_ports: 5000 
        image: manjarisri/todo:2
        network_mode: host 
        state: started
