---
- hosts: vm 
  become: true 
  connection: ssh
#   gather_facts: no
  tasks:
   - name: Read-write git checkout from github
     ansible.builtin.git:
      repo: https://github.com/manjarisri/ans.git
      dest: /home/ubuntu/ans
      single_branch: yes
      version: deploy

#    - name: copy app files
#      copy:
#       src: ./
#       dest: /var/www/myapp
   - name: deploy app
     command: pip3 install -r /home/ubuntu/ans/requirements.txt
     command: pip3 install Flash FLask-SQLAlchemy /home/ubuntu/ans

   - name: deploy app
     command: python3 /home/ubuntu/ans/todo.py
     
     
# RUN pip3 install -r requirements.txt

# COPY . .


# RUN pip3 install Flash FLask-SQLAlchemy
